[workspace]
authors = ["sam watts <sam.watts445@gmail.com>"]
channels = ["conda-forge"]
name = "backend"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
contextily = ">=1.6.2,<2"
ipykernel = ">=6.30.1,<7"
fastapi = ">=0.116.1,<0.117"
uvicorn = ">=0.35.0,<0.36"
pydantic = ">=2.11.7,<3"
diskcache = ">=5.6.3,<6"
pip = ">=25.2,<26"
osmnx = ">=2.0.6,<3"
numpy = ">=2.3.2,<3"
pandas = ">=2.3.2,<3"
networkx = ">=3.5,<4"
geopandas = ">=1.1.1,<2"
matplotlib = ">=3.10.5,<4"
scipy = ">=1.16.1,<2"
scikit-learn = ">=1.7.1,<2"
tabulate = ">=0.9.0,<0.10"
tqdm = ">=4.67.1,<5"
graph-tool = ">=2.98,<3"
