name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]   # or "master", depending on your repo

permissions:
  contents: write        # needed to push to gh-pages
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload site folder
        uses: actions/upload-pages-artifact@v3
        with:
          path: mapbox-frontend-app/src/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
